services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
    networks:
      - recipe_nest_network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgresRecipe
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - recipe_nest_network
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minioRecipe
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - recipe_nest_network
    volumes:
      - minio_data:/data
    command: server /data

networks:
  recipe_nest_network:
    driver: bridge

volumes:
  postgres_data: {}
  minio_data: {}
